In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
ds = pd.read_csv('../Data.csv')
#iloc[rows,cols]
X = ds.iloc[:,:-1].values
y = ds.iloc[:,3].values
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [4]:
from sklearn.preprocessing import Imputer, LabelEncoder, OneHotEncoder

#strategy can be most_frequent, mean, median
imputer = Imputer(strategy='most_frequent',axis=0)
#select which drop want to be replace with mean
imputer = imputer.fit(X[:, 1:3])
#transform column and replace the existing column
X[:, 1:3] = imputer.transform(X[:, 1:3])
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 48000.0],
       ['France', 35.0, 58000.0],
       ['Spain', 27.0, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [5]:
#convert to categorical value not ordinal value
X[:,0] = LabelEncoder().fit_transform(X[:,0])
y[:,] = LabelEncoder().fit_transform(y[:,])

In [6]:
#need to convert the label to dummy variables
onehotencoder = OneHotEncoder(categorical_features=[0])
X = onehotencoder.fit_transform(X).toarray()
X

array([[1.0e+00, 0.0e+00, 0.0e+00, 4.4e+01, 7.2e+04],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.7e+01, 4.8e+04],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.0e+01, 5.4e+04],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.8e+01, 6.1e+04],
       [0.0e+00, 1.0e+00, 0.0e+00, 4.0e+01, 4.8e+04],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.5e+01, 5.8e+04],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.7e+01, 5.2e+04],
       [1.0e+00, 0.0e+00, 0.0e+00, 4.8e+01, 7.9e+04],
       [0.0e+00, 1.0e+00, 0.0e+00, 5.0e+01, 8.3e+04],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.7e+01, 6.7e+04]])

In [7]:
#only yes/ no
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1], dtype=object)

In [8]:
#train test split example
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((8, 5), (2, 5), (8,), (2,))

In [9]:
#feature scaling
from sklearn.preprocessing import StandardScaler

#standardisation
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

'''do we need to apply feature scaling to dummy variables ? depends on the context - 
if you don't apply to feature scaling it won't break your models 
you don't need to apply feature scaling on y_train, y_test
'''
X_train, X_test

(array([[-1.        ,  2.64575131, -0.77459667,  0.4330127 , -1.1851228 ],
        [ 1.        , -0.37796447, -0.77459667,  0.        ,  0.59842834],
        [-1.        , -0.37796447,  1.29099445, -1.44337567, -1.1851228 ],
        [-1.        , -0.37796447,  1.29099445, -1.44337567, -0.80963835],
        [ 1.        , -0.37796447, -0.77459667,  1.58771324,  1.72488169],
        [-1.        , -0.37796447,  1.29099445,  0.14433757,  0.03520167],
        [ 1.        , -0.37796447, -0.77459667,  1.01036297,  1.0677839 ],
        [ 1.        , -0.37796447, -0.77459667, -0.28867513, -0.24641167]]),
 array([[-1.        ,  2.64575131, -0.77459667, -1.01036297, -0.62189612],
        [-1.        ,  2.64575131, -0.77459667,  1.87638837,  2.10036614]]))